name: First Demo Action

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Action started"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hello, World!"
      - name: Run a multiline script
        run: |
          echo Add other action to build,
          echo test, and deploy your project.
      - name: List files
        run: ls ${{ github.workplace }}
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ TOjSON(github)}}
        run: echo "$GITHUB_CONTEXT"
      - name: Action Complete




